[package]
name = "stonks"
version = "0.1.0"
edition = "2021"


[dependencies]
reqwest = { version = "0.12.3", features = ["json"]} 
serde = { version = "1.0.197", features = [ "derive" ] }
tokio = { version = "1.37.0", features = ["full"] }
